POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Yojan Regmi",
  "number": "0528706740"
}

###
GET http://localhost:3001/api/persons

###
DELETE http://localhost:3001/api/persons/how/5ebc983b63eeb44f2650422c

###
PUT http://localhost:3001/api/persons/5ebea97bfedd574bce121cfb
Content-Type: application/json

{
  "name": "yojan regmi",
  "number": 5555555555
}

###
GET http://localhost:3001/api/persons/5ebeae940e8c2854eca7cbec